 POST http://localhost:3001/api/user HTTP/1.1
 content-type: application/json

 {
 "email": "anna@gmail.com",
 "password": "ira",
 "firstname": "Annabella",
 "minit": "",
 "lastname": "Jallow"

 }

 



###
 POST http://localhost:3001/api/student HTTP/1.1
content-type: application/json

{
"email": "diva@gmail.com",
 "password": "mifa",
 "firstname": "Daiana",
 "minit": "",
 "lastname": "Manneh",
 "userId": "63947b5fef13c30b565584c8"
}


